theme: "jekyll-theme-cayman"
description: "CodeCaster.WindowsServices documentation"
url: "https://codecasternl.github.io/WindowsServiceExtensions/"
defaults:
  -
    scope:
      path: "" # everything
    values:
      layout: "cayman-with-menu"
