name: Build and publish .NET Core package

on:
  release:
    types: 
    - created
  
jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version info from Git
      id: git_version
      uses: battila7/get-version-action@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore CodeCaster.WindowsServiceExtensions.sln

    - name: Build
      run: dotnet build CodeCaster.WindowsServiceExtensions.sln --no-restore --configuration=Release -p:Version=${{ steps.git_version.outputs.version-without-v }}
  
    - name: Release to GitHub
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          fail_on_unmatched_files: true # needs action-gh-release@v2 but that doesn't exist yet, gives a warning now
          files: |
            **/*.nupkg
            **/*.snupkg

    - name: Release to NuGet.org
      if: startsWith(github.ref, 'refs/tags/')
      run: nuget push **/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
